import { Flex, Typography } from "antd"
import MainLayout from "components/layouts/MainLayout"
import React from "react"

const { Title, Paragraph } = Typography

type Props = {

}

const PrivacyPolicyPage: React.FC<Props> = () => {
  return (
    <MainLayout>
      <Flex
        vertical
        gap={16}
        className="p-lg"
      >
        <Title level={2}>Privacy Policy</Title>
        <Paragraph>
          Thank you for visiting reblock.finance (the “Website”). Your privacy is important to us. This Privacy Policy (the “Policy”) describes the types of information Reblock Technology Company (the “Company”, “us”, “we”, or “our”) may collect from you or that you may provide when you visit the Website and the products, features, materials, and services we offer (collectively with the Website, the “Services”). This Policy also describes our policies and procedures for collecting, using, maintaining, protecting, and disclosing that information. This Policy applies to information we collect on the Website and through your use of the Services generally (including when you register for an account), and through communications between you and the Website (including email, text, and other electronic messages). This Policy does not apply to information collected by third parties, including any websites, services, and applications that you elect to access through the Services. It also does not apply to any information collected by the Company offline or through any other means, including any other website operated by us or any third party (including our affiliates and subsidiaries). Please review this Policy carefully. By accessing or using the Services (or by clicking on “accept” or “agree” to this Policy when prompted), you agree to the terms of this Policy on behalf of yourself or the entity or organization that you represent. If you do not agree to any term in this Policy, you should refrain from further use of our Services. 1.Children Using or Accessing the Services. The Services and its content are not intended for, nor directed at, children under the age of eighteen (18). No one under the age of eighteen (18) may provide any personal information to or on the Services. Please note that we do not knowingly collect any personally identifiable information from children under the age of eighteen (18). If you are under the age of eighteen (18), please do not attempt to use or register for the Services or send any information about yourself to us, including your name, address, telephone number, or email address. If it is determined that we have inadvertently collected or received personally identifiable information from a child under the age of eighteen (18), we shall immediately take the necessary steps to ensure that such information is deleted from our system’s database.
        </Paragraph>
        <Paragraph>
        2.Changes to Our Privacy Policy. This Policy was last revised on the date noted at the top of this page. We may update this Policy from time to time. If we make material changes, we will post the updated Policy on this page and notify you of such changes by means of through a notice on the Website home page. Your continued use of the Services after we make changes is deemed to be acceptance of those changes, so please check the Policy periodically for updates.
        </Paragraph>
        <Paragraph>
        3.Information We Collect. We receive several types information about you from various sources, including (A) information and content that you give us; (B) automatically collected information. Each is described in detail below.
        </Paragraph>
        <Paragraph>
        3.1 Information and Content That You Give Us. We collect personal information that you knowingly choose to disclose. This may include:
        </Paragraph>
        <Paragraph>
        Personal Information. Personal information, such as your name, address, email address, phone number, username, password, Metamask account, and any other information you directly provide us on or through the Services. This includes information you provide when you register or create an account, or complete a questionnaire. Correspondences. Records and copies of your email messages together with your email address and our responses, if you choose to correspond with us through email. 3.2 Information We Collect Automatically. We may use a variety of technologies to collect certain information about your equipment, browsing actions, and patterns whenever you interact with the Services, including:
        </Paragraph>
        <Paragraph>
        Activity Information. Details of your visits to our Services, including the types of content you view or engage with; the features you use; the actions you take; the people or accounts you interact with; the time, frequency, and duration of your activities; and other information about your use of and actions on the Services. Equipment Information. Information about your computer and internet connection, including your computer operating system, public Ethereum address, IP address, browser type, and browser language. Location Information. Information about the location of your device, including GPS location, for purposes of enhancing or facilitating the Services. We may also use information about the location of the device you are using to help us understand how the Services and functionality are being used and to deliver more relevant advertising. The gathering of this information may be used for maintaining the quality of the Services we provide, as well as providing overall general statistics related to the use of the Services. The technologies we use for this automatic data collection may include:
        </Paragraph>
        <Paragraph>
          Cookies. A cookie is a small data file stored on the hard drive of your computer either for only the duration of your visit on a website (“session cookies”) or for a fixed period (“persistent cookies”). Cookies contain information that can later be read by a web server. We may use cookies to provide you with a more personal and interactive experience on the Services. JavaScripts. JavaScripts are code snippets embedded in websites and applications that facilitate a variety of operations including accelerating the refresh speed of certain functionality or monitoring usage of various online components. Entity Tags. Entity Tags are HTTP code mechanisms that allow portions of websites to be stored or “cached” within your browser and validates these caches when the website is opened, accelerating website performance since the web server does not need to send a full response if the content has not changed. HTML5 Local Storage. HTML5 local storage allows data from websites to be stored or “cached” within your browser to store and retrieve data in HTML5 pages when the website is revisited. This Policy does not cover the use of tracking technologies by third parties. The Services may contain links, content, advertising, or references to other websites by third parties, including advertisers, ad networks and servers, content providers, and application providers. These third parties may use cookies or other tracking technologies to collect information about you when you use the Services. The information they collect may be associated with your personal information or they may collect information about your online activities over time and across different websites. Please be aware that we do not control these third parties’ tracking technologies or when and how they may be used. Therefore, the Company does not claim nor accept responsibility for any privacy policies, practices, or procedures of any third party. We encourage you to read the privacy statements and terms and conditions of linked or referenced websites you enter. If you have any questions about an ad or other targeted content, you should contact the responsible provider directly.
        </Paragraph>
        <Paragraph>
        3.3 How We Use Your Information. We may use the information we collect about you in a variety of ways, including:
        </Paragraph>
        <Paragraph>
        to provide the Services and its content to you; to respond to comments and questions, and provide customer service; to fulfill the purpose for which you provide such information, or fulfill any other purpose disclosed by us when you provide the information; to communicate with you about your account, or subscription; to inform you about important changes to, or other news about, the Services or any of its features or content; to operate, maintain, improve, personalize, and analyze the Services; to monitor and analyze trends, usage, and activities for marketing or advertising purposes; to detect, prevent, or investigate security breaches, fraud, and other unauthorized or illegal activity; to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection; to maintain appropriate records for internal administrative purposes; in any other way we may describe when you provide the information; and for any other purpose with your consent. We may use the information we have collected from you to enable us to display advertisements to our advertisers’ target audiences. Even though we do not disclose your personal information for these purposes without your consent, if you click on or otherwise interact with an advertisement, the advertiser may assume that you meet its target criteria.
        </Paragraph>
        <Paragraph>
        4.How We Share Your Information. We may disclose aggregated or anonymized information about our users without any restrictions. We will not share your personal information that we collect or you provide as described in this Policy except in the following circumstances:
        </Paragraph>
        <Paragraph>
          With subsidiaries and affiliates for business purposes. To our subsidiaries and affiliated companies for purposes of management and analysis, decision-making, and other business purposes. When we work with service providers. To service providers, professional advisors, contractors, and other third parties that provide us with support services, such as payment processing, website hosting, information technology, sales, email and postal delivery, location mapping, product and service delivery, or analytics services, and who are bound by contractual obligations to keep personal information confidential and use it only for the purposes for which we disclose it to them. When we become involved in a sale or transfer of the Company. If we become involved with a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of the Company’s assets (whether as a going concern or as part of a bankruptcy, liquidation, or similar proceeding), to business entities or people involved in the negotiation or transfer. When we are required by law. To comply with any court order, law, or legal process, including to respond to any government or regulatory request. When we enforce our rights. To enforce or apply this Policy, our Terms of Use (https://reblock.finance/terms), and other agreements, including for billing and collection purposes. To help protect lawful interests. If we believe disclosure will help us protect the rights, property, or safety of the Company, our users, partners, agents, and others. This includes exchanging information with other companies and organizations for fraud protection, and spam and malware prevention. To fulfill the purpose for that information or with your consent. To fulfill the purpose for which you provide the information, for any other purpose disclosed by us when you provide the information, or with your consent. Information that you post on or through the public areas of the Services (e.g., in chat rooms, bulletin boards, and discussion groups) are generally accessible to, and may be collected and used by, others and may result in unsolicited messages or other forms of contact from others. Users of the Services are encouraged to exercise caution when providing personal information about themselves in public or interactive areas.
        </Paragraph>
        <Paragraph>
        5.Your Choices. 5.1 Mechanisms to Control Your Information. We strive to provide you with choices regarding the personal information you provide to us. We have created mechanisms to provide you with the following control over your information:
        </Paragraph>
        <Paragraph>
        Cookies and Other Tracking Technologies. You may be able to set your browser to reject cookies and certain other technologies by adjusting the appropriate settings in your browser. Each browser is different, but many common browsers have preferences that may be adjusted to allow you to either accept or reject cookies and certain other technologies before they are set or installed, or allow you to remove or reject the use or installation of certain technologies altogether. We recommend that you refer to the Help menu in your browser to learn how to modify your browser settings. Please note that you cannot remove Flash cookies simply by changing your browser settings. To learn how you can manage your Flash cookie settings, visit the Flash player settings page on Adobe’s website. If you disable or refuse cookies or other tracking technologies, please note that some parts of the Services may become inaccessible or may not function properly. Promotional Communications from the Company. If you do not wish to have your contact information used by the Company to promote our own or third-party products or services, you can opt out by (i) informing us of your preference at the time you ; (ii) modifying your user preferences in your account profile; (iii) following the opt-out instructions in the promotional emails we send you; or (iv) sending us an email stating your request. Please note that if you opt out of receiving promotional communications from us, we may still send you transactional communications, including emails about your account or purchases. 5.2 How We Respond to Do Not Track Signals “Do Not Track” is a privacy preference you can set in most web browsers. When you turn on this preference, it sends a signal or message to the websites you visit indicating that you do not wish to be tracked. Please note that we currently do not respond to Do Not Track browser settings.
        </Paragraph>
        <Paragraph>
        6.Accessing and Correcting Your Information. You may send us an email to request access to, correct, or remove any personal information that you have provided to us.
        </Paragraph>
        <Paragraph>
        We may not accommodate a request to change information if we believe the change would violate any law or legal requirement or cause the information to be incorrect.
        </Paragraph>
        <Paragraph>
        7.How We Protect Your Information. We take reasonable precautions to secure your personal information. We have implemented technical, physical, and administrative security measures designed to reduce the risk of loss, misuse, unauthorized access, disclosure, or modification of your information. We have put in place appropriate physical, electronic, and managerial procedures to safeguard the information we collect. All information you provide to us is stored on secure servers behind firewalls.
        </Paragraph>
        <Paragraph>
        The safety and security of your information also depend on you. Where we have given you (or where you have chosen) a password for access to certain parts of the Services, you are responsible for keeping this password confidential. We ask you not to share your password with anyone.
        </Paragraph>
        <Paragraph>
        While we have employed security technologies and procedures to assist safeguarding your personal information, no system or network can be guaranteed to be 100% secure. Unauthorized entry or use, hardware or software failure, and other factors may compromise the security of user information at any time. Any transmission of personal information is at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Website or any other Services.
        </Paragraph>
        <Paragraph>
        8.Terms of Use. If you choose to visit the Services, your visit and any dispute over privacy is subject to this Policy and our Terms of Use (https://reblock.finance/terms), including limitations on damages, resolution of disputes, and application of the law of the state of Indonesia.
        </Paragraph>
        <Paragraph>
        9.Contact Us. We welcome your questions, comments, and concerns about privacy. You can contact us at admin@reblock.finance.
        </Paragraph>
      </Flex>
    </MainLayout>
  )
}

export default PrivacyPolicyPage