name: Deploy to Juno

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_PUBLIC_URL: ${{ vars.REACT_APP_PUBLIC_URL }}
      REACT_APP_RB_ORI_CANISTER_ID: ${{ vars.REACT_APP_RB_ORI_CANISTER_ID }}
      REACT_APP_NNS_LEDGER_CANISTER_ID: ${{ vars.REACT_APP_NNS_LEDGER_CANISTER_ID }}
      REACT_APP_NNS_CANISTER_ID: ${{ vars.REACT_APP_NNS_CANISTER_ID }}
      REACT_APP_KYC_PERSONA_ENV_ID: ${{ secrets.REACT_APP_KYC_PERSONA_ENV_ID }}
      REACT_APP_KYC_PERSONA_TEMPLATE_ID: ${{ secrets.REACT_APP_KYC_PERSONA_TEMPLATE_ID }}
      REACT_APP_WALLET_CONNECT_PROJECT_ID: ${{ secrets.REACT_APP_WALLET_CONNECT_PROJECT_ID }}
      REACT_APP_SATELLITE_ID: ${{ secrets.REACT_APP_SATELLITE_ID }}
      REACT_APP_INFURA_KEY: ${{ secrets.REACT_APP_INFURA_KEY }}
      REACT_APP_ALCHEMY_KEY: ${{ secrets.REACT_APP_ALCHEMY_KEY }}
      REACT_APP_RBSVC_HOST: ${{ secrets.REACT_APP_RBSVC_HOST }}
      
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "19"

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy to Juno
        uses: buildwithjuno/juno-action@main
        with:
          args: deploy
        env:
          JUNO_TOKEN: ${{ secrets.JUNO_TOKEN }}
